# gitleaks設定ファイル
# 機密情報検出のルール定義

# タイトル
title = "Charactier AI Gitleaks Config"

# 許可リスト（誤検知を防ぐ）
[allowlist]
description = "Allowlisted files and patterns"
regexes = [
    # 例: example_secret, mock_key などのテスト用文字列を許可
    '''example_''',
    '''mock_''',
    '''test_''',
    '''dummy_''',
    '''placeholder''',
    '''YOUR_.*_HERE''',
    '''<.*>''',
]
paths = [
    # ドキュメントファイルは除外
    '''README\.md''',
    '''CLAUDE\.md''',
    '''docs/.*''',
    '''.gitleaks.toml''',
    '''package-lock\.json''',
    '''yarn\.lock''',
    '''pnpm-lock\.yaml''',
]

# カスタムルール
[[rules]]
id = "jwt-secret"
description = "JWT Secret Key"
regex = '''JWT_SECRET\s*=\s*['"][^'"]+['"]'''
tags = ["key", "jwt"]

[[rules]]
id = "openai-api-key"
description = "OpenAI API Key"
regex = '''(?i)(openai[_\-]?api[_\-]?key|OPENAI_API_KEY)\s*[:=]\s*['"]?sk-[a-zA-Z0-9]{48}['"]?'''
tags = ["key", "openai"]

[[rules]]
id = "stripe-key"
description = "Stripe API Key"
regex = '''(?i)(stripe[_\-]?(secret|publishable)?[_\-]?key|STRIPE_SECRET_KEY)\s*[:=]\s*['"]?(sk|pk)_(test|live)_[0-9a-zA-Z]{24,}['"]?'''
tags = ["key", "stripe"]

[[rules]]
id = "sendgrid-key"
description = "SendGrid API Key"
regex = '''(?i)(sendgrid[_\-]?api[_\-]?key|SENDGRID_API_KEY)\s*[:=]\s*['"]?SG\.[a-zA-Z0-9]{22}\.[a-zA-Z0-9]{43}['"]?'''
tags = ["key", "sendgrid"]

[[rules]]
id = "mongodb-uri"
description = "MongoDB Connection String"
regex = '''mongodb(\+srv)?://[^:]+:[^@]+@[^/\s]+'''
tags = ["database", "mongodb"]

[[rules]]
id = "redis-url"
description = "Redis Connection URL"
regex = '''redis://[^:]+:[^@]+@[^/\s]+'''
tags = ["database", "redis"]

[[rules]]
id = "generic-api-key"
description = "Generic API Key"
regex = '''(?i)(api[_\-]?key|apikey|api_secret|api[_\-]?token)\s*[:=]\s*['"][a-zA-Z0-9_\-]{20,}['"]'''
tags = ["key", "generic"]

[[rules]]
id = "private-key"
description = "Private Key"
regex = '''-----BEGIN (RSA |EC |DSA |OPENSSH )?PRIVATE KEY-----'''
tags = ["key", "private"]

[[rules]]
id = "aws-access-key"
description = "AWS Access Key"
regex = '''(?i)(aws[_\-]?access[_\-]?key[_\-]?id|aws[_\-]?secret[_\-]?access[_\-]?key)\s*[:=]\s*['"]?[A-Z0-9]{16,}['"]?'''
tags = ["key", "aws"]

# 日本語の機密情報パターン
[[rules]]
id = "japanese-password"
description = "Japanese Password Pattern"
regex = '''(?i)(パスワード|暗証番号|認証コード)\s*[:：=]\s*['"]?[^'"\s]+['"]?'''
tags = ["password", "japanese"]