# Gitleaks設定ファイル
# https://github.com/gitleaks/gitleaks

[allowlist]
# 環境変数サンプルファイルは除外
paths = [
  '''.env.example''',
  '''\.env\.example$''',
  '''backend/\.env\.example$''',
  '''docs/.*\.md$''',
  '''README\.md$''',
  '''CLAUDE\.md$'''
]

# テストファイルやモックデータは除外
files = [
  '''.*_test\..*''',
  '''.*\.test\..*''',
  '''.*\.spec\..*''',
  '''test-.*''',
  '''tests/.*''',
  '''__tests__/.*''',
  '''mock.*''',
  '''example.*'''
]

# 偽のシークレットパターンを許可
regexes = [
  '''sk-xxx\.\.\.''',
  '''sk_test_xxx\.\.\.''',
  '''sk_live_xxx\.\.\.''',
  '''whsec_xxx\.\.\.''',
  '''SG\.xxx\.\.\.''',
  '''your-super-secret.*''',
  '''test-secret.*''',
  '''change-in-production''',
  '''mongodb://localhost:27017/.*''',
  '''redis://localhost:6379'''
]

# コミットメッセージのホワイトリスト
commits = [
  '''example''',
  '''test''',
  '''mock''',
  '''dummy''',
  '''sample''',
  '''placeholder'''
]

[[rules]]
description = "Ignore example secrets"
regex = '''(?i)(password|secret|key|token)\s*=\s*["']?(your-|test-|example-|xxx|change-in-production)'''
tags = ["example", "test"]

[[rules]]
description = "Ignore localhost URLs"
regex = '''(mongodb|redis|http|https)://localhost'''
tags = ["localhost", "development"]