name: e2e
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:7
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        run: |
          pnpm install
          cd frontend && pnpm install && cd ..
          cd backend && pnpm install && cd ..
      - name: Install Playwright
        run: npx playwright install --with-deps chromium
      - name: Build
        run: cd frontend && npm run build
      - name: Lint & Type Check
        run: |
          npm run lint
          npm run type-check
      - name: Setup test data
        run: cd backend && node src/scripts/seed-test-data.js
        env:
          MONGO_URI: mongodb://localhost:27017/test
      - name: Run E2E tests
        env:
          MONGO_URI: mongodb://localhost:27017/test
          NODE_ENV: test
          JWT_SECRET: test-secret
          JWT_REFRESH_SECRET: test-refresh-secret
          FRONTEND_URL: http://localhost:3000
          DISABLE_RATE_LIMIT: true
          TEST_USER_EMAIL: global-test@example.com
          TEST_USER_PASSWORD: Test123!
        run: |
          cd backend && npm run dev > ../backend.log 2>&1 &
          cd ../frontend && npm run start > ../frontend.log 2>&1 &
          npx wait-on http://localhost:5000/api/v1/health http://localhost:3000 -t 60000
          npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
      - name: Show logs on failure
        if: failure()
        run: |
          echo "=== Backend logs ==="
          cat backend.log || true
          echo "=== Frontend logs ==="
          cat frontend.log || true