name: E2E Tests

on:
  # 手動実行
  workflow_dispatch:
    inputs:
      browsers:
        description: 'ブラウザ選択'
        required: false
        default: 'all'
        type: choice
        options:
          - all
          - chromium
          - firefox
          - webkit
  
  # プルリクエスト時は自動実行（オプション）
  pull_request:
    types: [opened, synchronize]
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      LANG: ja_JP.UTF-8
      LC_ALL: ja_JP.UTF-8
    services:
      mailhog:
        image: mailhog/mailhog
        ports: ['1025:1025', '8025:8025']
      # stripe:
      #   image: stripe/stripe-cli
      #   ports: ['12111:12111']
      # minio:
      #   image: minio/minio:latest
      #   env:
      #     MINIO_ROOT_USER: minio
      #     MINIO_ROOT_PASSWORD: minio123
      #   ports: 
      #     - 9000:9000
      #   options: >-
      #     --health-cmd "curl -f http://localhost:9000/minio/health/live || exit 1"
      #     --health-interval 10s
      #     --health-timeout 5s
      #     --health-retries 5
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Install root dependencies
        run: pnpm install --no-frozen-lockfile
        
      - name: Install frontend dependencies
        run: |
          cd frontend
          pnpm install --no-frozen-lockfile
        
      - name: Install Playwright browsers and dependencies
        run: |
          sudo npx playwright install-deps
          npx playwright install --with-deps
        
      - name: Run E2E tests
        run: |
          if [ "${{ github.event.inputs.browsers }}" = "all" ]; then
            npm run test:e2e
          else
            npm run test:e2e -- --project=${{ github.event.inputs.browsers }}
          fi
        
      - name: Generate failure report
        run: |
          npm run failures:md || echo "No test results found"
        if: always()
        
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: |
            playwright-report
            coverage/playwright-results.json
            coverage/failures.md