name: E2E Tests

on:
  # 手動実行
  workflow_dispatch:
    inputs:
      browsers:
        description: 'ブラウザ選択'
        required: false
        default: 'all'
        type: choice
        options:
          - all
          - chromium
          - firefox
          - webkit
  
  # プルリクエスト時は自動実行（オプション）
  pull_request:
    types: [opened, synchronize]
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mailhog:
        image: mailhog/mailhog
        ports: ['1025:1025', '8025:8025']
      stripe:
        image: stripe/stripe-cli
        ports: ['12111:12111']
      minio:
        image: minio/minio
        env:
          MINIO_ACCESS_KEY: minio
          MINIO_SECRET_KEY: minio123
        command: server /data
        ports: ['9000:9000']
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        
      - name: Run E2E tests
        run: |
          if [ "${{ github.event.inputs.browsers }}" = "all" ]; then
            npm run test:e2e
          else
            npm run test:e2e -- --project=${{ github.event.inputs.browsers }}
          fi
        
      - name: Generate failure report
        run: npm run failures:md
        if: always()
        
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: |
            playwright-report
            coverage/playwright-results.json
            coverage/failures.md