name: E2E Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write  # PRへのコメント投稿用（将来の機能拡張用）

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      # バージョンは package.json の packageManager フィールドから自動検出
        
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'pnpm'
        
    - name: Install dependencies
      run: pnpm install
      
    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps
      
    - name: Generate test specs
      run: pnpm run gen:specs
      
    - name: Run Playwright tests
      run: pnpm run test:e2e
      env:
        PLAYWRIGHT_BASE_URL: http://localhost:3000
        
    - name: Generate coverage report
      if: always()
      run: pnpm run coverage:report
      
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
        
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: coverage-report
        path: coverage/
        retention-days: 30